export default {
  companies: [
    {
      name: "@Clinikli",
      period: "Nov 2021 - August 2022",
      role: "UI Engineer",
      points: [
        "Built a robust and scalable user interface for a medical appointment booking web application using Vue.js, Tailwind CSS, and JavaScript.",
        "Worked closely with the back-end developer and UI designer to ensure seamless integration and delivery of features.",
        "Utilized Vuex state management for secure and reliable management of large user data.",
        "Implemented performance optimization techniques, such as lazy loading and code splitting, to improve the app's speed and efficiency across devices and browsers.",
        "Integrated necessary libraries and performed unit testing using Jest to ensure code quality and increase user experience flow.",
        "Developed a complaint contact feature for users to reach out to verified physicians for counsel and quick meetups in case of emergencies before actual appointments.",
        "Designed and delivered pixel-perfect UIs with sleek and dynamic integrations to provide a smooth user experience.",
        "Contributed to the development of heavy load intentions for the app, using Vue.js for its lightweight property, making it fast and scalable.",
        "Ensured compatibility and efficiency by writing highly secure code, compatible with various devices and browsers.",
        "Owned and delivered on features, meeting requirements in terms of performance, and scalability.",
      ],
    },
    {
      name: "@Sonvisage",
      period: "August 2021 - March 2022",
      role: "UI Engineer",
      points: [
        "Rebuilt and managed the user interface for an IoT company's web application, Sonvisage, which collected data from millions of users.",
        "Wrote modern, clean, and manageable code for a major component of the app to ensure data collection and management were seamless.",
        "Utilized Vuex state management for secure and reliable management of large user data.",
        "Optimized the UI performance of the application by utilizing Vue.js, and only using necessary libraries, especially in the data visualization components.",
        "Played a significant role in handling continuous integration for the frontend to ensure the delivery of high-quality code and uncompromised integrity.",
        "Resolved the form data issue for different form types, enabling the smooth pulling of categorical data on different admin sections.",
        "Developed an admin system for verifying and managing data uploaders, and the entire project and product.",
        "Managed the display and sale of IoT machines, ensuring their smooth integration with the app.",
        "Ensured the stability and lightweight property of the application, making it scalable, fast, and compatible with various devices and browsers.",
        "Owned and delivered features on project within the stipulated time, meeting up in terms of performance, scalability, and efficiency.",
      ],
    },
    {
      name: "@Vinca",
      period: "June 2021 - August 2021",
      role: "Frontend Engineer",
      intro: `Built the entire Ui of the web-app, which would be handling appointment booking and clients management, alongside communication`,
      points: [
        "Developed and implemented a simple and minimalistic web app using React and Node for flexibility and rendering, for Vinca Hospital to handle hospital appointment booking and management.",
        "Utilized React Hooks for handling form complexities, filling, and submission, ensuring the app was easy to use for all types of users.",
        "Wrote highly performant and scalable React code, ensuring all code components were working effectively and removing excess chunks to achieve a lightweight and speedy app.",
        "Built the entire front-end architecture from scratch to completion, including the implementation of the design and unit testing to ensure all code components were working efficiently.",
        "Integrated an automated admin system responsible for receiving all booked appointments, appointment confirmation, appointment canceling, and appointment rescheduling, making the app easy to manage and maintain.",
        "Utilized Styled Components for styling and Vanilla CSS for the formal implementation of CSS properties",
        "Ensured the app was compatible with various devices and browsers, providing a seamless user experience for all users.",
        "Delivered the project, and all features within the stipulated time, meeting all requirements and exceeding client expectations in terms of functionality, performance, and efficiency.",
      ],
    },
    {
      name: "@FourthStream",
      period: "December 2020 - April 2021",
      role: "Frontend Developer",
      points: [
        "Designed and built a user interface for FourthStream, a financial investment company's web application to handle customer investment and payment, schedule investment terms, and calculate ROI.",
        "Collaborated with the back-end developer to build a scalable app that ensured payments were credited based on ROI to users' wallets at the end of each investment tenure.",
        "Developed a sleek UI using functional principles, ensuring UI consistency and code stability, while utilizing CSS, HTML, and JavaScript alongside NodeJs.",
        "Wrote robust code for the user interface that enhanced easy interaction for users, providing a seamless user experience.",
        "Interacted with the testers and stakeholders to implement requested features, ensuring the app met all requirements and exceeded client expectations.",
        "Ensured the platform was secured and scalable for users alongside the admin system, providing efficient financial management for the company and its clients.",
        "Ensured compatibility with various devices and browsers, providing a seamless user experience for all users.",
      ],
    },
  ],
  technologies: [
    "Typescript",
    "ReactJs",
    "NextJs",
    "NodeJs",
    "VueJs",
    "NuxtJs",
    "JavaScript(ES6+)",
    "HTML & CSS(SCSS)",
    "Figma & Sketch",
  ],
  others: [
    "Performance Optimization",
    "Technical Writing",
    "End-To-End Testing",
    "Design Systems",
    "Build Automation",
    "Progressive Enhancement",
    "SE Optimization",
    "AWS DevOps",
  ],
};
